export type DemoCitation = { source: string; detail: string; preview: string };
export type DemoScenario = { question: string; answer: string; citations: DemoCitation[] };
export const demoSources = ["Neural Networks.pdf", "Lecture 08.vtt", "Attention Is All You Need.pdf", "System Design.md"];
export const demoScenarios: DemoScenario[] = [
  { question: "How does attention help a language model understand context?", answer: "Self-attention allows every token to compare itself with every other token in the sequence. Instead of processing text one word at a time, Transformers attend to all tokens simultaneously, allowing them to capture long-range dependencies efficiently.", citations: [{ source: "Attention Is All You Need.pdf", detail: "Page 4", preview: "Attention connects each token to the other tokens that shape its meaning." }, { source: "Lecture 08.vtt", detail: "18:42", preview: "The lecture explains how attention weights create contextual representations." }] },
  { question: "Explain transformers in simple terms", answer: "Transformers are models that learn which parts of a sequence matter to one another. Attention lets them process relationships in parallel, making them both powerful and efficient for language tasks.", citations: [{ source: "Attention Is All You Need.pdf", detail: "Page 3", preview: "The Transformer is based solely on attention mechanisms." }] },
  { question: "Summarize these notes", answer: "The notes describe a system that breaks information into meaningful pieces, retrieves the most relevant context, and uses that context to produce grounded answers.", citations: [{ source: "System Design.md", detail: "Retrieval layer", preview: "Relevant chunks are selected before the answer is composed." }] },
  { question: "Compare the two technical sources", answer: "The paper presents the formal architecture, while the lecture provides an intuitive explanation of the same mechanism. Together they connect the equations with the practical behavior of attention.", citations: [{ source: "Attention Is All You Need.pdf", detail: "Page 4", preview: "Scaled dot-product attention computes relationships between tokens." }, { source: "Lecture 08.vtt", detail: "21:07", preview: "A visual example shows attention shifting toward related words." }] },
  { question: "Generate a study guide", answer: "Review self-attention, query-key-value projections, positional information, and why parallel attention captures long-range dependencies. Finish by explaining one example in your own words.", citations: [{ source: "System Design.md", detail: "Study checklist", preview: "Break each concept into a definition, diagram, and applied example." }] },
];
