"use client";
import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import { SectionHeading, glass } from "@/components/landing/shared";
import { demoScenarios } from "./demo-data";
import { DemoSources } from "./demo-sources";
import { DemoChat } from "./demo-chat";
export function DemoSection() { const [scenarioIndex, setScenarioIndex] = useState(0); const [input, setInput] = useState(""); const [phase, setPhase] = useState<"idle" | "searching" | "finding" | "answer">("idle"); const [active, setActive] = useState<string | null>(null); const timer = useRef<number[]>([]); const scenario = demoScenarios[scenarioIndex]; const reset = (next = (scenarioIndex + 1) % demoScenarios.length) => { timer.current.forEach(window.clearTimeout); setScenarioIndex(next); setInput(""); setActive(null); setPhase("idle"); }; const submit = () => { if (!input.trim() || phase !== "idle") return; setPhase("searching"); timer.current.push(window.setTimeout(() => setPhase("finding"), 800)); timer.current.push(window.setTimeout(() => setPhase("answer"), 1600)); }; useEffect(() => { const idle = window.setTimeout(() => { timer.current.forEach(window.clearTimeout); setScenarioIndex((current) => (current + 1) % demoScenarios.length); setInput(""); setActive(null); setPhase("idle"); }, 15000); return () => window.clearTimeout(idle); }, [scenarioIndex, phase]); useEffect(() => () => timer.current.forEach(window.clearTimeout), []); return <section id="demo" className="relative scroll-mt-24 px-4 py-24 sm:px-6 sm:py-32"><div className="absolute left-1/2 top-1/2 -z-10 h-80 w-2/3 -translate-x-1/2 rounded-full bg-violet-600/[.08] blur-[120px]" /><SectionHeading eyebrow="See Lumina think" title="Ask once. Understand the whole picture." copy="A quiet, source-aware workspace for questions that deserve more than a search result." /><motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} className={`${glass} mx-auto mt-12 max-w-5xl overflow-hidden rounded-3xl`}><div className="flex items-center gap-2 border-b border-white/[.08] px-4 py-3 sm:px-5"><span className="grid size-7 place-items-center rounded-lg bg-violet-500/15 text-violet-300"><Sparkles className="size-3.5" /></span><span className="text-sm font-medium">Machine Learning Crash Course</span><span className="ml-auto hidden text-[10px] text-zinc-500 sm:block">4 sources indexed</span></div><div className="flex min-h-[430px]"><DemoSources active={active} onSelect={setActive} /><DemoChat scenario={scenario} input={input} onInput={setInput} onSubmit={submit} phase={phase} onSource={setActive} /></div></motion.div></section>; }
