"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ChevronDown, ChevronUp, FileText, GitBranch, Mic2, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SectionHeading, glass } from "./shared";

export function ProductDemo() {
  const [asked, setAsked] = useState(false);
  const [citationsOpen, setCitationsOpen] = useState(false);
  return <section id="demo" className="relative scroll-mt-24 px-4 py-24 sm:px-6 sm:py-32"><div className="absolute left-1/2 top-1/2 -z-10 h-80 w-2/3 -translate-x-1/2 rounded-full bg-violet-600/[.08] blur-[120px]" />
    <SectionHeading eyebrow="See Lumina think" title="Ask once. Understand the whole picture." copy="A quiet, source-aware workspace for questions that deserve more than a search result." />
    <motion.div initial={{ opacity: 0, y: 32, scale: .98, filter: "blur(8px)" }} whileInView={{ opacity: 1, y: 0, scale: 1, filter: "blur(0px)" }} viewport={{ once: true, amount: .2 }} transition={{ type: "spring", stiffness: 68, damping: 18, mass: 1 }} className={`${glass} mx-auto mt-12 max-w-5xl overflow-hidden rounded-3xl`}>
      <div className="flex items-center justify-between border-b border-white/[.08] px-4 py-3 sm:px-5"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-violet-500/15 text-violet-300"><Sparkles className="size-3.5" /></span><span className="text-sm font-medium">Machine Learning Crash Course</span></div><span className="hidden rounded-full border border-white/[.08] px-2.5 py-1 text-[10px] text-zinc-400 sm:block">12 sources indexed</span></div>
      <div className="grid min-h-[390px] md:grid-cols-[190px_1fr]"><aside className="hidden border-r border-white/[.08] bg-white/[.018] p-4 md:block"><p className="px-2 text-[10px] font-semibold uppercase tracking-[.18em] text-zinc-500">Sources</p><div className="mt-3 space-y-1">{["Neural networks.pdf", "Lecture 08", "Attention is all you need"].map((source, i) => <div key={source} className="flex items-center gap-2 rounded-lg px-2 py-2 text-xs text-zinc-400"><FileText className="size-3.5 text-violet-300" />{source}<span className="ml-auto text-[10px] text-zinc-600">{i + 2}</span></div>)}</div></aside>
        <div className="flex flex-col p-4 sm:p-6"><div className="flex-1"><div className="rounded-2xl border border-violet-300/15 bg-violet-500/[.07] p-4 text-sm text-violet-100">How does attention help a language model understand context?</div><AnimatePresence mode="wait">{asked ? <motion.div key="answer" initial={{ opacity: 0, y: 10, filter: "blur(5px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} exit={{ opacity: 0 }} transition={{ duration: .45 }} className="pt-5"><p className="text-sm leading-7 text-zinc-300">Attention lets a model weigh every relevant token in a sequence instead of processing context as a fixed summary. It can connect a word to the parts of a sentence that most shape its meaning, even when they are far apart.</p><p className="mt-3 text-sm leading-7 text-zinc-400">In practice, this makes context selective and parallel—so the model can focus on the relationships that matter for the next prediction.</p><button onClick={() => setCitationsOpen(!citationsOpen)} className="mt-4 flex items-center gap-2 rounded-lg border border-violet-300/15 bg-violet-400/[.08] px-3 py-2 text-xs font-medium text-violet-200 transition-all hover:border-violet-300/35 hover:bg-violet-400/[.15]">2 citations {citationsOpen ? <ChevronUp className="size-3.5" /> : <ChevronDown className="size-3.5" />}</button><AnimatePresence>{citationsOpen && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="mt-2 grid gap-2 sm:grid-cols-2"><div className="rounded-lg border border-white/[.08] bg-black/20 p-3 text-xs text-zinc-400"><span className="font-medium text-white">Attention is All You Need</span><br />Section 3.2 · p. 5</div><div className="rounded-lg border border-white/[.08] bg-black/20 p-3 text-xs text-zinc-400"><span className="font-medium text-white">Lecture 08: Transformers</span><br />08:14–09:02</div></div></motion.div>}</AnimatePresence><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" size="sm" className="border-white/10 bg-white/[.04] text-zinc-300 hover:bg-white/[.1]"><Mic2 className="mr-1.5 size-3.5" /> Make podcast</Button><Button variant="outline" size="sm" className="border-white/10 bg-white/[.04] text-zinc-300 hover:bg-white/[.1]"><GitBranch className="mr-1.5 size-3.5" /> Build roadmap</Button></div></motion.div> : <div className="pt-5 text-sm text-zinc-500">Lumina is ready to search across 12 sources.</div>}</AnimatePresence></div>
          <div className="mt-6 flex items-center gap-2 rounded-xl border border-white/[.1] bg-black/30 p-2 pl-4"><span className="flex-1 text-sm text-zinc-500">Ask a follow-up question…</span><button onClick={() => setAsked(true)} aria-label="Ask question" className="grid size-8 place-items-center rounded-lg bg-violet-500 text-white transition-all hover:-translate-y-0.5 hover:bg-violet-400"><Send className="size-3.5" /></button></div></div>
      </div>
    </motion.div>
  </section>;
}
