"use client";

import { motion } from "framer-motion";
import { Brain, FileUp, MessageCircle, SearchCode, Sparkles } from "lucide-react";
import { SectionHeading, glass } from "./shared";
const steps = [{title:"Upload",copy:"Drop in the material you want to understand.",icon:FileUp},{title:"Index",copy:"Lumina maps every source into a private knowledge graph.",icon:SearchCode},{title:"Retrieve",copy:"Relevant context appears instantly for every question.",icon:MessageCircle},{title:"Chat",copy:"Explore ideas with citations that keep you grounded.",icon:Brain},{title:"Learn",copy:"Turn insight into recall with your personal study toolkit.",icon:Sparkles}];
export function Timeline() { return <section id="how-it-works" className="px-4 py-24 sm:px-6 sm:py-32"><SectionHeading eyebrow="From source to understanding" title="A better way to make knowledge useful." />
 <motion.div className="relative mx-auto mt-14 max-w-5xl" initial="hidden" whileInView="visible" viewport={{once:true,amount:.12}} variants={{visible:{transition:{delayChildren:.22,staggerChildren:.34}}}}><div className="absolute bottom-6 left-6 top-6 w-px bg-gradient-to-b from-violet-400/70 via-violet-400/25 to-transparent md:bottom-auto md:left-6 md:right-6 md:top-6 md:h-px md:w-auto md:bg-gradient-to-r" /> <div className="grid gap-4 md:grid-cols-5">{steps.map(({title,copy,icon:Icon}, i) => <motion.div key={title} variants={{hidden:{opacity:0,y:30,filter:"blur(9px)"},visible:{opacity:1,y:0,filter:"blur(0px)",transition:{type:"spring",stiffness:68,damping:18,mass:1}}}} className="relative pl-16 md:pl-0 md:pt-16"><span className="absolute left-0 top-0 z-10 grid size-12 place-items-center rounded-2xl border border-violet-300/25 bg-violet-500/15 text-violet-200 shadow-[0_0_25px_rgba(139,92,246,.18)] md:left-0"><Icon className="size-5" /></span><article className={`${glass} min-h-32 rounded-2xl p-4 transition-all hover:-translate-y-1 hover:border-violet-400/40 hover:shadow-[0_14px_40px_rgba(139,92,246,.12)] md:p-5`}><span className="text-xs font-medium text-violet-300">0{i+1}</span><h3 className="mt-2 font-medium">{title}</h3><p className="mt-2 text-xs leading-5 text-zinc-400">{copy}</p></article></motion.div>)}</div></motion.div>
 </section>; }
